### ISSUE TITLE
Fix error in create_log_entry example

### ISSUE THREAD

**Issue by lkatalin** [sigstore/sigstore-rs#104]
The current example [reports that it may return an error](https://github.com/sigstore/sigstore-rs/blob/main/examples/rekor/create_log_entry/main.rs#L41-L66).

We should change the example to (by default) create fresh entry data (this requires either a new test file or a new signing key or both, I don't remember offhand but it can be tested), upload this data to Rekor, and then clean up after itself.

**Comment by jvanz** [comment]
I'm working on this
