### ISSUE TITLE
Add OCI container image signing

### ISSUE THREAD

**Issue by Xynnn007** [sigstore/sigstore-rs#125]
**Description**

Like the counterpart in `sigstore/cosign`, implement OCI container image signing.

**Comment by lukehinds** [comment]
Sounds good to me, as long as we implement as a mod (which I am sure is what you intend to do).

**Comment by Xynnn007** [comment]
> Sounds good to me, as long as we implement as a mod (which I am sure is what you intend to do).

Yes, after the signing key mod is prepared. I'd like to take this.

**Comment by Xynnn007** [comment]
Development plan:
- [ ] Impl `push` functions for `registry::ClientCapabilities` for the ability of communicating with OCI registry
- [ ] Impl basic architecture of OCI image-signing, including two modular parts:
    * signer interface
    * payload structure
- [ ] impl signer interface using `key_interface`
- [ ] examples and documents

**Comment by dlorenc** [comment]
FYI that the OCI has finally approved the official mechanism for storing signatures a few weeks ago: https://github.com/opencontainers/wg-reference-types/

You'll likely need to switch to this over time as registries update to include it. I'd still recommend starting with the existing cosign version though.

**Comment by Xynnn007** [comment]
> FYI that the OCI has finally approved the official mechanism for storing signatures a few weeks ago: https://github.com/opencontainers/wg-reference-types/
> 
> You'll likely need to switch to this over time as registries update to include it. I'd still recommend starting with the existing cosign version though.

I've read roughly the docs. Are you referring that we can store the signature via the `referrers` registry's API?

**Comment by dlorenc** [comment]
Yes, that's the plan in cosign, but it's definitely early and no registries support it yet. Just flagging it to put it in your radar!
