### ISSUE TITLE
Propose Xynnn007 as maintainer

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore-rs#126]
@Xynnn007 has done some solid work in sigstore-rs around implementing and refining the key interfaces and plans more work around an OCI interface. 

I would like to propose we promote Xynnn007 to maintainer (codeowner)

@Xynnn007 please ack if you would like the role

Other maintainers please vote +1 / -1 or abstain

cc @flavio @viccuad @arsa

**Comment by flavio** [comment]
I'm in favor of that: :+1:

**Comment by Xynnn007** [comment]
Thanks, I'd like to
