### ISSUE TITLE
Provide pure async variants for OIDC flows.

### ISSUE THREAD

**Issue by bobmcwhirter** [sigstore/sigstore-rs#129]
Current implementation of the OIDC flows requires blocking tasks.

This is limiting when applications are otherwise using `awc` which leads to using `actix_rt` for async executors.

Providing `async_http_client` variants for `auth_url()` and `redirect_listener()` would remove this limitation.

**note** this issue provided for tracking on a PR I'm opening.

**Comment by jvanz** [comment]
Considering that the PR of this issue is closed. I think this issue can be closed as well.

**Comment by flavio** [comment]
Closing, we now have async implementations of both `auth_url` and `redirect_listener`
