### ISSUE TITLE
Add ability to parse Rekor LogEntry

### ISSUE THREAD

**Issue by lkatalin** [sigstore/sigstore-rs#150]
The `LogEntry.body` for example should not just be a String, but a typed struct where you can access subfields and extract data.

**Comment by Neccolini** [comment]
If nobody is already working on this issue, I'd like to give it a try !
But before I start, just to confirm, am I correct that the change required here is to change the type of `LogEntry.body`  (`String` now) to `Body` which is implemented [here](https://github.com/sigstore/sigstore-rs/blob/main/src/rekor/models/log_entry.rs#L29) ?
