### ISSUE TITLE
verify example is confusing

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore-rs#17]
https://github.com/sigstore/sigstore-rs/tree/main/examples/verify

I don''t understand why someone would provide a a cert email, fuclio cert and rekor pub key to verify the signing made with a cosign generated key. There is no trust relation between the cosign.pub key and the others.

I would have thought this would be more relevant:

`cargo run --example verify -- -k cosign.pub  registry-testing.svc.lan/busybox`

or for keyless:

```
cargo run --example verify -- \
  --rekor-pub-key ~/.sigstore/root/targets/rekor.pub \
  --fulcio-crt fulcio.crt.pem \
  registry-testing.svc.lan/busybox
```

**Comment by flavio** [comment]
Right now the library is extremely conservative. When looking at all the signature layers of a cosign signature, the library attempts to verify the trustworthiness of each layer:

  * Layers produced without rekor integration enabled and with "traditional" key signing are always trusted
  * Layers produced with rekor integration and "traditional" key signing are trusted only if the rekor bundle is verified. For that we need the public key of rekor
  * Layers produced with keyless signing are trusted only if the rekor bundle is verified and if the certificate has been issued by fulcio's CA. For that we need both the public key of rekor and fulcio's certificate.

The trusted layers are then further filtered based on other input data, such as user email, annotations,...

I could change the behaviour of the library and make the fulcio and rekor data optional. When the user doesn't provide them the library will simply ignore (== consider not trusted) the layers that require rekor's public key and fulcio's certificate to be verified.

As for the mandatory email address that the example program requires, this is clearly a mistake. It should be made optional

What do you think about the proposal?

**Comment by flavio** [comment]
I think we can close it right now, this has been merged
