### ISSUE TITLE
blob verification fails when used with unsanitized base64 signature strings

### ISSUE THREAD

**Issue by jleightcap** [sigstore/sigstore-rs#288]
**Description**

When verifying a signature passed via a file, trailing newlines are not sanitized.

Using the [`verify_blob`](https://github.com/sigstore/sigstore-rs/blob/main/src/cosign/mod.rs#L163-L174) API with a signature file generated by sigstore-python, [`verify_signature`](https://github.com/sigstore/sigstore-rs/blob/main/src/crypto/verification_key.rs#L263-L267) fails with

```
Error: Invalid byte 10, offset 96.
```

the root issue seems to be differing signature files generated between sigstore-python and cosign (e.g. https://github.com/sigstore/sigstore-rs/tree/main/examples/cosign/verify-blob#sign-the-artifacttxt-file-using-cosign).

(byte 10 == '`\n`')

This is pretty easily fixed with a `.trim()` at the `fs::read_to_string` callsite, but compatibility doesn't seem guaranteed between sigstore clients.

**Version**

https://github.com/sigstore/sigstore-rs/commit/e23046c72ecaf3d4fd63540ed538d8972ac61468

**Comment by jku** [comment]
the errors are not quite the same now: 
`Verification failed Base64DecodeError(InvalidByte(0, 45))`

I'll have a look at the code but the differences I can see in the data are:
* python adds a linefeed to signature, ocsign does not
* python uses PEM with ascii armoring for certificate. cosign uses PEM with ascii armoring _encoded in base64 (???)_

**Comment by jku** [comment]
Verified in code: there are two differences that would need to be handled to make verify-blob work with data from sigstore-python:
* trim the signature -- this seems reasonable
* Avoid base64 decoding the certificate -- this is not as clearly useful as you'd now need two code paths

**Comment by jku** [comment]
I will make an attempt at fixing this, I think it looks like something the CLI layer can take care of.
