### ISSUE TITLE
Automate crates publish of releases

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore-rs#30]
Perhaps we should utilise a GH action too `cargo publish` each release?

https://github.com/marketplace/actions/publish-crates

cc @flavio @cpanato

**Comment by lukehinds** [comment]
This could be a nice intro task to the project for @cburkhardt27 as well.

**Comment by cpanato** [comment]
i missed this notification sorry :(

**Comment by flavio** [comment]
Sure, sounds fine with me. However this might not be possible in the short term. The library is about to depend on a fork of `oci-distribution`, which doesn't make it possible to publish the crate on crates.io.

I'm a maintainer of oci-distribution, I'll work to address this issue asap.

**Comment by lukehinds** [comment]
> Sure, sounds fine with me. However this might not be possible in the short term. The library is about to depend on a fork of `oci-distribution`, which doesn't make it possible to publish the crate on crates.io.
> 
> I'm a maintainer of oci-distribution, I'll work to address this issue asap.

what do you think we are taking (rough estimate), perhaps 2 weeks or so? I am thinking @cburkhardt27 could work on setting it up in the meantime, and we go live with it once the  oci-distribution required patches have landed?
