### ISSUE TITLE
Cannot load cosign generated key pairs with empty password

### ISSUE THREAD

**Issue by gmpinder** [sigstore/sigstore-rs#380]
**Description**

I've been working on integrating this crate into my CLI program and I ran into a situation where pem files generated by the cosign tool with an empty password couldn't be loaded. 

```bash
COSIGN_PASSWORD="" COSIGN_YES="true" cosign generate-key-pair
```

I was getting `Failed to parse the key: Unsupported key type`, so I dug into why that was and found that the keys were being processed differently if the password had no length. Since the cosign CLI tool appears to allow the use of an empty password, then I believe that this should change to be in parity.

**Version**
0.9.0

**Comment by gmpinder** [comment]
@flavio any possibility to get this out in a `v0.9.1` patch?

**Comment by flavio** [comment]
I can't, the release is stuck because we're waiting for https://github.com/awslabs/tough/pull/769 to be merged and for a new version of the tough crate to include it :sob:
