### ISSUE TITLE
tests fail with "failed to start registry"

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-rs#402]
**Description**

`make test` fails all `cosign::tests::sign_verify_image` tests:
```
thread 'cosign::tests::sign_verify_image::case_1' panicked at src/cosign/mod.rs:573:14:
failed to start registry: Client(Init(SocketNotFoundError("/var/run/docker.sock")))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Do tests need docker daemon to run? This does not seem to be documented anywhere...

**Version**

current git main (e53636062).

**Comment by flavio** [comment]
Yes, it does require the docker daemon to be running. We're using [testcontainers](https://crates.io/crates/testcontainers) for that

**Comment by jku** [comment]
yes, confirmed things work if docker daemon is running and user has permissions to start a container
