### ISSUE TITLE
Add  Víctor Cuadrado Juan to the list of maintainers

### ISSUE THREAD

**Issue by flavio** [sigstore/sigstore-rs#46]
**Description**

I would like @viccuad to become one of the maintainers of `sigstore-rs`. Lately he has been helping a lot with code reviews, plus he already [contributed code fixes and enhancements](https://github.com/sigstore/sigstore-rs/graphs/contributors).

**Comment by lukehinds** [comment]
sounds good to me!

**Comment by viccuad** [comment]
Thanks both for the confidence :).
