### ISSUE TITLE
import rekor crate

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore-rs#86]
Import [rekor-rs](https://github.com/jyotsna-penumaka/rekor-rs) to this repository.

ToDo:

- [x] import code (obviously) to `src/rekor/`
- [ ] implement CI job to verify fresh / latest code-gen from openapi (this might need some thinking about, how do we insure code is update?)
- [ ] verify docs look correct
- [ ] cut a release

cc @jyotsna-penumaka / @flavio

**Comment by lukehinds** [comment]
@cpanato , you might be very useful for helping with automation of the CI based refresh of the openAPI / swagger code generation.

**Comment by cpanato** [comment]
@lukehinds @flavio @jyotsna-penumaka how we generate the openAPI/swagger today?

**Comment by lukehinds** [comment]
@cpanato I think its an NPM library. @jyotsna-penumaka has done it a few times.

**Comment by cpanato** [comment]
@lukehinds yep, i was waiting for the rekor PR get in so can i start the work
