### ISSUE TITLE
Fix cosign tests failing due to certs "not issued by a trusted root"

### ISSUE THREAD

**Issue by lkatalin** [sigstore/sigstore-rs#94]
**Description**

Cosign tests are failing. See original [comment](https://github.com/sigstore/sigstore-rs/pull/88#issuecomment-1225914688).
Tests output [here](https://github.com/sigstore/sigstore-rs/runs/7998727587?check_suite_focus=true)

**Version**

Latest

**Comment by lkatalin** [comment]
Update: these aren't failing on my local system. :thinking:

**Comment by greyspectrum** [comment]
I can take this.

**Comment by lkatalin** [comment]
@greyspectrum Looks like this may already be fixed on the main branch, our two open PRs just need to be rebased on there.
